#!/usr/bin/env bash
# ==============================================================================
# Script: generate_env_file.sh
# Location: testing/generate_env_file.sh
# Purpose: Dynamically generates a fresh Ed25519 keypair and writes testing/.env
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DP1_CLI_DIR="$(cd "${SCRIPT_DIR}/../dp1-cli" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
BIN="${DP1_CLI_DIR}/dp1"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}[GENERATE-ENV] Generating fresh cryptographic keypair for test environment...${NC}"

# Ensure dp1 binary is built in dp1-cli repository
if [[ ! -x "${BIN}" ]]; then
    echo -e "${BLUE}[GENERATE-ENV] Building dp1 binary in ${DP1_CLI_DIR}...${NC}"
    (cd "${DP1_CLI_DIR}" && go build -o dp1 .)
fi

# Generate random Ed25519 keypair using dp1 CLI
KEY_JSON=$("${BIN}" key generate --json)

# Parse output fields using Python
KEYS_PARSED=$(python3 -c "
import sys, json
data = json.loads(sys.argv[1])
did = data['public_did_key']
pub_hex = data['public_hex']
priv_hex = data['private_key_hex_expanded']
print(f'{did}|{pub_hex}|{priv_hex}')
" "${KEY_JSON}")

IFS='|' read -r DP1_CURATOR_KID DP1_PUBLIC_KEY DP1_PRIVATE_KEY <<< "${KEYS_PARSED}"

if [[ -z "${DP1_CURATOR_KID}" || -z "${DP1_PRIVATE_KEY}" ]]; then
    echo -e "${RED}[GENERATE-ENV] Failed to parse generated keypair!${NC}" >&2
    exit 1
fi

cat <<EOF > "${ENV_FILE}"
# Suite 1 Test Environment Secrets & Configuration
# Dynamically generated by testing/generate_env_file.sh

DP1_FEED_BASE_URL="https://feed.feralfile.com"
DP1_PRIVATE_KEY="${DP1_PRIVATE_KEY}"
DP1_PUBLIC_KEY="${DP1_PUBLIC_KEY}"
DP1_CURATOR_KID="${DP1_CURATOR_KID}"
# FIXTURE_ID="C01"
# TEST_FIXTURE_PATH="./testing/playlists/playlist1.json"
EOF

chmod 600 "${ENV_FILE}"
echo -e "${GREEN}[GENERATE-ENV] ✓ Successfully generated fresh .env at ${ENV_FILE}${NC}"
echo -e "${GREEN}  Curator DID Key: ${DP1_CURATOR_KID}${NC}"
